# Generated by Django 4.0.3 on 2024-01-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0002_keytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytoken',
            name='public_key',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='keytoken',
            name='refresh_token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
