# Generated by Django 4.0.3 on 2024-03-19 01:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0002_doctor_patient_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='test_images/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.test')),
            ],
        ),
    ]
