# Generated by Django 4.0.3 on 2024-03-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0003_remove_test_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
