# Generated by Django 4.0.3 on 2024-01-09 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medicalManagerWeb.core.enums
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0003_alter_keytoken_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicaluser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersignuprequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('medical_history_columns', models.TextField()),
                ('observation_columns', models.TextField()),
                ('treatment_columns', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[(medicalManagerWeb.core.enums.GENDER['M'], 'Male'), (medicalManagerWeb.core.enums.GENDER['F'], 'Female'), (medicalManagerWeb.core.enums.GENDER['O'], 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('note', models.TextField(blank=True)),
                ('allergies', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicalManagerWeb.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reason_for_visit', models.CharField(max_length=255)),
                ('symptom', models.CharField(max_length=255)),
                ('medical_history', models.TextField()),
                ('vital_signs', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateField(auto_now=True)),
                ('observation', models.TextField(blank=True)),
                ('diagnosis', models.CharField(max_length=255)),
                ('treatment_plan', models.TextField()),
                ('version', models.IntegerField(editable=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.patient')),
                ('primary_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.doctor')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.template')),
            ],
            options={
                'unique_together': {('record_id', 'version')},
            },
        ),
    ]
