# Generated by Django 4.0.3 on 2024-01-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0004_alter_keytoken_id_alter_medicaluser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='vital_signs',
            field=models.TextField(),
        ),
    ]
