# Generated by Django 4.0.3 on 2024-01-09 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0005_alter_record_vital_signs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.record')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.template')),
            ],
        ),
    ]
