# Generated by Django 4.0.3 on 2024-03-28 00:20

from django.db import migrations, models
import medicalManagerWeb.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0005_test_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(upload_to=medicalManagerWeb.models.upload_path),
        ),
    ]
