# Generated by Django 4.0.3 on 2024-01-08 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0006_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('medical_history_columns', models.TextField()),
                ('observation_columns', models.TextField()),
                ('treatment_columns', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reason_for_visit', models.CharField(max_length=255)),
                ('symptom', models.CharField(max_length=255)),
                ('medical_history', models.TextField()),
                ('vital_signs', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateField(auto_now=True)),
                ('observation', models.TextField(blank=True)),
                ('diagnosis', models.CharField(max_length=255)),
                ('treatment_plan', models.TextField()),
                ('version', models.IntegerField(editable=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.patient')),
                ('primary_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.doctor')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.template')),
            ],
            options={
                'unique_together': {('record_id', 'version')},
            },
        ),
    ]
