# Generated by Django 4.0.3 on 2024-01-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0009_alter_template_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
