# Generated by Django 4.0.3 on 2024-01-16 10:32

from django.db import migrations, models
import medicalManagerWeb.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0010_alter_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[(medicalManagerWeb.core.enums.GENDER['M'], medicalManagerWeb.core.enums.GENDER['M']), (medicalManagerWeb.core.enums.GENDER['F'], medicalManagerWeb.core.enums.GENDER['M']), (medicalManagerWeb.core.enums.GENDER['O'], medicalManagerWeb.core.enums.GENDER['O'])], max_length=1),
        ),
    ]
