# Generated by Django 4.0.3 on 2024-01-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0011_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'F'), ('O', 'O')], max_length=1),
        ),
    ]
