# Generated by Django 4.0.3 on 2024-01-17 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0013_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='version',
        ),
    ]
