# Generated by Django 4.0.3 on 2024-03-13 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0014_alter_record_unique_together_alter_record_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaluser',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='usersignuprequest',
            name='display_name',
        ),
    ]
