# Generated by Django 4.0.3 on 2024-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0015_remove_medicaluser_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
