# Generated by Django 4.0.3 on 2024-03-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0016_alter_medicaluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignuprequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usersignuprequest',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
