# Generated by Django 4.0.3 on 2024-03-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0017_alter_usersignuprequest_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('user', 'first_name', 'last_name')},
        ),
    ]
