# Generated by Django 4.0.3 on 2024-03-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0020_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
    ]
