# Generated by Django 4.0.3 on 2024-03-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0021_doctor_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
