# Generated by Django 4.0.3 on 2024-03-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0022_alter_doctor_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
