# Generated by Django 4.0.3 on 2024-03-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0023_remove_patient_name_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
