# Generated by Django 4.0.3 on 2024-03-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalManagerWeb', '0024_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default='eadec51ec302413a8b02358900c783e3', on_delete=django.db.models.deletion.CASCADE, to='medicalManagerWeb.doctor'),
            preserve_default=False,
        ),
    ]
